### ISSUE TITLE
react-native int AwesomeProject hangs on Windows

### ISSUE THREAD

**Issue by JobbyM** [JobbyM/react-native-learning#1]
## 问题背景
1. platform：window 7
2. node：v6.3.0
3. npm：3.10.3
4. react-native-cli：1.0.0
## 问题描述
1. 按照 https://facebook.github.io/react-native/docs/getting-started.html 进行测试
2. 运行如下代码：

``` cmd
react-native init AwesomeProject --verbose
```
1. 出现如下提示：

``` cmd
This will walk you through creating a new React Native project in D:\AwesomeProject
Installing react-native package from npm...
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn npm ENOENT
    at exports._errnoException (util.js:1008:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Module.runMain (module.js:577:11)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3

```

**Comment by JobbyM** [comment]
## 问题解决
1. 参考进行 https://github.com/facebook/react-native/issues/7681 解决
2. 解决步骤如下：

``` cmd
react-native init AwesomeProject
cd AwesomeProject
npm install react-native --save
react-native android
react-native run-android
react-native start
```
